version: "3.7"
services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
          - SA_PASSWORD=Dev12345
          - ACCEPT_EULA=Y
        ports:
          - "5434:1433"
