version: "3.7"
services:
    sqldata:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
          - SA_PASSWORD=sqlserver
          - ACCEPT_EULA=Y
        ports:
          - "5434:1433"
